version: "3.9"

services:
  web:
    image: sherazhowlader/sherazdev:latest
    container_name: sherazdev
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:80"

  mariadb:
    image: mysql:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mdSHIraj@123
      MYSQL_DATABASE: sherazdev
    ports:
    - 3333:3306

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
