name: CI/CD
on:
  push:
    branches:
      - test-ci-cd
jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none

      - name: Use Composer dependencies cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/composer
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Use npm dependencies cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress --optimize-autoloader --no-dev
          npm install
          npm install husky --save-dev
          npm run build

      - name: Compress deployment artifacts
        run: |
          tar --create --gzip \
            --exclude="bootstrap/cache/*" \
            --exclude="node_modules" \
            --exclude="public/storage" \
            --exclude="storage" \
            --file ~/artifacts.tar.gz * .github/deployment

      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployment-artifacts
          path: ~/artifacts.tar.gz
          retention-days: 1

  deploy-dev:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/test-ci-cd'
    runs-on: "ubuntu-22.04"
    steps:
      - name: Download deployment artifacts
        uses: actions/download-artifact@v4
        with:
          name: deployment-artifacts

      - name: Extract artifact
        run: |
          mkdir deploy
          tar -xf artifacts.tar.gz -C deploy

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: deploy/
          server-dir: /public_html
          log-level: verbose
          timeout: 60
